// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: app.proto

package com.sid.thermostat.app.protobuf;

public interface ConfigurationRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:thermostat.app.ConfigurationRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string requestId = 1;</code>
   */
  java.lang.String getRequestId();
  /**
   * <code>string requestId = 1;</code>
   */
  com.google.protobuf.ByteString
      getRequestIdBytes();

  /**
   * <code>string config_topic = 2;</code>
   */
  java.lang.String getConfigTopic();
  /**
   * <code>string config_topic = 2;</code>
   */
  com.google.protobuf.ByteString
      getConfigTopicBytes();

  /**
   * <code>string data_topic = 3;</code>
   */
  java.lang.String getDataTopic();
  /**
   * <code>string data_topic = 3;</code>
   */
  com.google.protobuf.ByteString
      getDataTopicBytes();

  /**
   * <code>int32 data_interval = 4;</code>
   */
  int getDataInterval();
}
