// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: app.proto

package com.sid.thermostat.app.protobuf;

/**
 * Protobuf type {@code thermostat.app.ConfigurationRequest}
 */
public  final class ConfigurationRequest extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:thermostat.app.ConfigurationRequest)
    ConfigurationRequestOrBuilder {
private static final long serialVersionUID = 0L;
  // Use ConfigurationRequest.newBuilder() to construct.
  private ConfigurationRequest(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private ConfigurationRequest() {
    requestId_ = "";
    configTopic_ = "";
    dataTopic_ = "";
  }

  @java.lang.Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return this.unknownFields;
  }
  private ConfigurationRequest(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    this();
    if (extensionRegistry == null) {
      throw new java.lang.NullPointerException();
    }
    int mutable_bitField0_ = 0;
    com.google.protobuf.UnknownFieldSet.Builder unknownFields =
        com.google.protobuf.UnknownFieldSet.newBuilder();
    try {
      boolean done = false;
      while (!done) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            done = true;
            break;
          case 10: {
            java.lang.String s = input.readStringRequireUtf8();

            requestId_ = s;
            break;
          }
          case 18: {
            java.lang.String s = input.readStringRequireUtf8();

            configTopic_ = s;
            break;
          }
          case 26: {
            java.lang.String s = input.readStringRequireUtf8();

            dataTopic_ = s;
            break;
          }
          case 32: {

            dataInterval_ = input.readInt32();
            break;
          }
          default: {
            if (!parseUnknownField(
                input, unknownFields, extensionRegistry, tag)) {
              done = true;
            }
            break;
          }
        }
      }
    } catch (com.google.protobuf.InvalidProtocolBufferException e) {
      throw e.setUnfinishedMessage(this);
    } catch (java.io.IOException e) {
      throw new com.google.protobuf.InvalidProtocolBufferException(
          e).setUnfinishedMessage(this);
    } finally {
      this.unknownFields = unknownFields.build();
      makeExtensionsImmutable();
    }
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return com.sid.thermostat.app.protobuf.App.internal_static_thermostat_app_ConfigurationRequest_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return com.sid.thermostat.app.protobuf.App.internal_static_thermostat_app_ConfigurationRequest_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            com.sid.thermostat.app.protobuf.ConfigurationRequest.class, com.sid.thermostat.app.protobuf.ConfigurationRequest.Builder.class);
  }

  public static final int REQUESTID_FIELD_NUMBER = 1;
  private volatile java.lang.Object requestId_;
  /**
   * <code>string requestId = 1;</code>
   */
  public java.lang.String getRequestId() {
    java.lang.Object ref = requestId_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      requestId_ = s;
      return s;
    }
  }
  /**
   * <code>string requestId = 1;</code>
   */
  public com.google.protobuf.ByteString
      getRequestIdBytes() {
    java.lang.Object ref = requestId_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      requestId_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int CONFIG_TOPIC_FIELD_NUMBER = 2;
  private volatile java.lang.Object configTopic_;
  /**
   * <code>string config_topic = 2;</code>
   */
  public java.lang.String getConfigTopic() {
    java.lang.Object ref = configTopic_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      configTopic_ = s;
      return s;
    }
  }
  /**
   * <code>string config_topic = 2;</code>
   */
  public com.google.protobuf.ByteString
      getConfigTopicBytes() {
    java.lang.Object ref = configTopic_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      configTopic_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int DATA_TOPIC_FIELD_NUMBER = 3;
  private volatile java.lang.Object dataTopic_;
  /**
   * <code>string data_topic = 3;</code>
   */
  public java.lang.String getDataTopic() {
    java.lang.Object ref = dataTopic_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      dataTopic_ = s;
      return s;
    }
  }
  /**
   * <code>string data_topic = 3;</code>
   */
  public com.google.protobuf.ByteString
      getDataTopicBytes() {
    java.lang.Object ref = dataTopic_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      dataTopic_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int DATA_INTERVAL_FIELD_NUMBER = 4;
  private int dataInterval_;
  /**
   * <code>int32 data_interval = 4;</code>
   */
  public int getDataInterval() {
    return dataInterval_;
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (!getRequestIdBytes().isEmpty()) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 1, requestId_);
    }
    if (!getConfigTopicBytes().isEmpty()) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 2, configTopic_);
    }
    if (!getDataTopicBytes().isEmpty()) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 3, dataTopic_);
    }
    if (dataInterval_ != 0) {
      output.writeInt32(4, dataInterval_);
    }
    unknownFields.writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (!getRequestIdBytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, requestId_);
    }
    if (!getConfigTopicBytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(2, configTopic_);
    }
    if (!getDataTopicBytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(3, dataTopic_);
    }
    if (dataInterval_ != 0) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt32Size(4, dataInterval_);
    }
    size += unknownFields.getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof com.sid.thermostat.app.protobuf.ConfigurationRequest)) {
      return super.equals(obj);
    }
    com.sid.thermostat.app.protobuf.ConfigurationRequest other = (com.sid.thermostat.app.protobuf.ConfigurationRequest) obj;

    if (!getRequestId()
        .equals(other.getRequestId())) return false;
    if (!getConfigTopic()
        .equals(other.getConfigTopic())) return false;
    if (!getDataTopic()
        .equals(other.getDataTopic())) return false;
    if (getDataInterval()
        != other.getDataInterval()) return false;
    if (!unknownFields.equals(other.unknownFields)) return false;
    return true;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    hash = (37 * hash) + REQUESTID_FIELD_NUMBER;
    hash = (53 * hash) + getRequestId().hashCode();
    hash = (37 * hash) + CONFIG_TOPIC_FIELD_NUMBER;
    hash = (53 * hash) + getConfigTopic().hashCode();
    hash = (37 * hash) + DATA_TOPIC_FIELD_NUMBER;
    hash = (53 * hash) + getDataTopic().hashCode();
    hash = (37 * hash) + DATA_INTERVAL_FIELD_NUMBER;
    hash = (53 * hash) + getDataInterval();
    hash = (29 * hash) + unknownFields.hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static com.sid.thermostat.app.protobuf.ConfigurationRequest parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.sid.thermostat.app.protobuf.ConfigurationRequest parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.sid.thermostat.app.protobuf.ConfigurationRequest parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.sid.thermostat.app.protobuf.ConfigurationRequest parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.sid.thermostat.app.protobuf.ConfigurationRequest parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.sid.thermostat.app.protobuf.ConfigurationRequest parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.sid.thermostat.app.protobuf.ConfigurationRequest parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.sid.thermostat.app.protobuf.ConfigurationRequest parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.sid.thermostat.app.protobuf.ConfigurationRequest parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static com.sid.thermostat.app.protobuf.ConfigurationRequest parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.sid.thermostat.app.protobuf.ConfigurationRequest parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.sid.thermostat.app.protobuf.ConfigurationRequest parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(com.sid.thermostat.app.protobuf.ConfigurationRequest prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code thermostat.app.ConfigurationRequest}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:thermostat.app.ConfigurationRequest)
      com.sid.thermostat.app.protobuf.ConfigurationRequestOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.sid.thermostat.app.protobuf.App.internal_static_thermostat_app_ConfigurationRequest_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.sid.thermostat.app.protobuf.App.internal_static_thermostat_app_ConfigurationRequest_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.sid.thermostat.app.protobuf.ConfigurationRequest.class, com.sid.thermostat.app.protobuf.ConfigurationRequest.Builder.class);
    }

    // Construct using com.sid.thermostat.app.protobuf.ConfigurationRequest.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessageV3
              .alwaysUseFieldBuilders) {
      }
    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      requestId_ = "";

      configTopic_ = "";

      dataTopic_ = "";

      dataInterval_ = 0;

      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return com.sid.thermostat.app.protobuf.App.internal_static_thermostat_app_ConfigurationRequest_descriptor;
    }

    @java.lang.Override
    public com.sid.thermostat.app.protobuf.ConfigurationRequest getDefaultInstanceForType() {
      return com.sid.thermostat.app.protobuf.ConfigurationRequest.getDefaultInstance();
    }

    @java.lang.Override
    public com.sid.thermostat.app.protobuf.ConfigurationRequest build() {
      com.sid.thermostat.app.protobuf.ConfigurationRequest result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public com.sid.thermostat.app.protobuf.ConfigurationRequest buildPartial() {
      com.sid.thermostat.app.protobuf.ConfigurationRequest result = new com.sid.thermostat.app.protobuf.ConfigurationRequest(this);
      result.requestId_ = requestId_;
      result.configTopic_ = configTopic_;
      result.dataTopic_ = dataTopic_;
      result.dataInterval_ = dataInterval_;
      onBuilt();
      return result;
    }

    @java.lang.Override
    public Builder clone() {
      return super.clone();
    }
    @java.lang.Override
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.setField(field, value);
    }
    @java.lang.Override
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return super.clearField(field);
    }
    @java.lang.Override
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return super.clearOneof(oneof);
    }
    @java.lang.Override
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, java.lang.Object value) {
      return super.setRepeatedField(field, index, value);
    }
    @java.lang.Override
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.addRepeatedField(field, value);
    }
    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof com.sid.thermostat.app.protobuf.ConfigurationRequest) {
        return mergeFrom((com.sid.thermostat.app.protobuf.ConfigurationRequest)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(com.sid.thermostat.app.protobuf.ConfigurationRequest other) {
      if (other == com.sid.thermostat.app.protobuf.ConfigurationRequest.getDefaultInstance()) return this;
      if (!other.getRequestId().isEmpty()) {
        requestId_ = other.requestId_;
        onChanged();
      }
      if (!other.getConfigTopic().isEmpty()) {
        configTopic_ = other.configTopic_;
        onChanged();
      }
      if (!other.getDataTopic().isEmpty()) {
        dataTopic_ = other.dataTopic_;
        onChanged();
      }
      if (other.getDataInterval() != 0) {
        setDataInterval(other.getDataInterval());
      }
      this.mergeUnknownFields(other.unknownFields);
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      com.sid.thermostat.app.protobuf.ConfigurationRequest parsedMessage = null;
      try {
        parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        parsedMessage = (com.sid.thermostat.app.protobuf.ConfigurationRequest) e.getUnfinishedMessage();
        throw e.unwrapIOException();
      } finally {
        if (parsedMessage != null) {
          mergeFrom(parsedMessage);
        }
      }
      return this;
    }

    private java.lang.Object requestId_ = "";
    /**
     * <code>string requestId = 1;</code>
     */
    public java.lang.String getRequestId() {
      java.lang.Object ref = requestId_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        requestId_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string requestId = 1;</code>
     */
    public com.google.protobuf.ByteString
        getRequestIdBytes() {
      java.lang.Object ref = requestId_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        requestId_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string requestId = 1;</code>
     */
    public Builder setRequestId(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      requestId_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>string requestId = 1;</code>
     */
    public Builder clearRequestId() {
      
      requestId_ = getDefaultInstance().getRequestId();
      onChanged();
      return this;
    }
    /**
     * <code>string requestId = 1;</code>
     */
    public Builder setRequestIdBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      requestId_ = value;
      onChanged();
      return this;
    }

    private java.lang.Object configTopic_ = "";
    /**
     * <code>string config_topic = 2;</code>
     */
    public java.lang.String getConfigTopic() {
      java.lang.Object ref = configTopic_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        configTopic_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string config_topic = 2;</code>
     */
    public com.google.protobuf.ByteString
        getConfigTopicBytes() {
      java.lang.Object ref = configTopic_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        configTopic_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string config_topic = 2;</code>
     */
    public Builder setConfigTopic(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      configTopic_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>string config_topic = 2;</code>
     */
    public Builder clearConfigTopic() {
      
      configTopic_ = getDefaultInstance().getConfigTopic();
      onChanged();
      return this;
    }
    /**
     * <code>string config_topic = 2;</code>
     */
    public Builder setConfigTopicBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      configTopic_ = value;
      onChanged();
      return this;
    }

    private java.lang.Object dataTopic_ = "";
    /**
     * <code>string data_topic = 3;</code>
     */
    public java.lang.String getDataTopic() {
      java.lang.Object ref = dataTopic_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        dataTopic_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string data_topic = 3;</code>
     */
    public com.google.protobuf.ByteString
        getDataTopicBytes() {
      java.lang.Object ref = dataTopic_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        dataTopic_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string data_topic = 3;</code>
     */
    public Builder setDataTopic(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      dataTopic_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>string data_topic = 3;</code>
     */
    public Builder clearDataTopic() {
      
      dataTopic_ = getDefaultInstance().getDataTopic();
      onChanged();
      return this;
    }
    /**
     * <code>string data_topic = 3;</code>
     */
    public Builder setDataTopicBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      dataTopic_ = value;
      onChanged();
      return this;
    }

    private int dataInterval_ ;
    /**
     * <code>int32 data_interval = 4;</code>
     */
    public int getDataInterval() {
      return dataInterval_;
    }
    /**
     * <code>int32 data_interval = 4;</code>
     */
    public Builder setDataInterval(int value) {
      
      dataInterval_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>int32 data_interval = 4;</code>
     */
    public Builder clearDataInterval() {
      
      dataInterval_ = 0;
      onChanged();
      return this;
    }
    @java.lang.Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFields(unknownFields);
    }

    @java.lang.Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:thermostat.app.ConfigurationRequest)
  }

  // @@protoc_insertion_point(class_scope:thermostat.app.ConfigurationRequest)
  private static final com.sid.thermostat.app.protobuf.ConfigurationRequest DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new com.sid.thermostat.app.protobuf.ConfigurationRequest();
  }

  public static com.sid.thermostat.app.protobuf.ConfigurationRequest getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<ConfigurationRequest>
      PARSER = new com.google.protobuf.AbstractParser<ConfigurationRequest>() {
    @java.lang.Override
    public ConfigurationRequest parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return new ConfigurationRequest(input, extensionRegistry);
    }
  };

  public static com.google.protobuf.Parser<ConfigurationRequest> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<ConfigurationRequest> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public com.sid.thermostat.app.protobuf.ConfigurationRequest getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

