// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: app.proto

package com.sid.thermostat.app.protobuf;

public interface DataOrBuilder extends
    // @@protoc_insertion_point(interface_extends:thermostat.app.Data)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string serial_no = 1;</code>
   */
  java.lang.String getSerialNo();
  /**
   * <code>string serial_no = 1;</code>
   */
  com.google.protobuf.ByteString
      getSerialNoBytes();

  /**
   * <code>uint64 device_time = 2;</code>
   */
  long getDeviceTime();

  /**
   * <code>float temperature = 3;</code>
   */
  float getTemperature();
}
