// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: app.proto

package com.sid.thermostat.app.protobuf;

public interface ProvisioningRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:thermostat.app.ProvisioningRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string serial_no = 1;</code>
   */
  java.lang.String getSerialNo();
  /**
   * <code>string serial_no = 1;</code>
   */
  com.google.protobuf.ByteString
      getSerialNoBytes();

  /**
   * <code>string ip_address = 2;</code>
   */
  java.lang.String getIpAddress();
  /**
   * <code>string ip_address = 2;</code>
   */
  com.google.protobuf.ByteString
      getIpAddressBytes();

  /**
   * <code>string mac_address = 3;</code>
   */
  java.lang.String getMacAddress();
  /**
   * <code>string mac_address = 3;</code>
   */
  com.google.protobuf.ByteString
      getMacAddressBytes();
}
