// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: app.proto

package com.sid.thermostat.app.protobuf;

public interface ProvisioningResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:thermostat.app.ProvisioningResponse)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string serial_no = 1;</code>
   */
  java.lang.String getSerialNo();
  /**
   * <code>string serial_no = 1;</code>
   */
  com.google.protobuf.ByteString
      getSerialNoBytes();

  /**
   * <code>string in_config_topic = 2;</code>
   */
  java.lang.String getInConfigTopic();
  /**
   * <code>string in_config_topic = 2;</code>
   */
  com.google.protobuf.ByteString
      getInConfigTopicBytes();

  /**
   * <code>string out_config_topic = 3;</code>
   */
  java.lang.String getOutConfigTopic();
  /**
   * <code>string out_config_topic = 3;</code>
   */
  com.google.protobuf.ByteString
      getOutConfigTopicBytes();

  /**
   * <code>string in_data_topic = 4;</code>
   */
  java.lang.String getInDataTopic();
  /**
   * <code>string in_data_topic = 4;</code>
   */
  com.google.protobuf.ByteString
      getInDataTopicBytes();

  /**
   * <code>.thermostat.app.ProvisioningResponse.ProvStatus status = 5;</code>
   */
  int getStatusValue();
  /**
   * <code>.thermostat.app.ProvisioningResponse.ProvStatus status = 5;</code>
   */
  com.sid.thermostat.app.protobuf.ProvisioningResponse.ProvStatus getStatus();

  /**
   * <code>int32 qos = 6;</code>
   */
  int getQos();
}
