// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: app.proto

package com.sid.thermostat.app.protobuf;

public interface ProvisioningResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:thermostat.app.ProvisioningResponse)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string serial_no = 1;</code>
   */
  java.lang.String getSerialNo();
  /**
   * <code>string serial_no = 1;</code>
   */
  com.google.protobuf.ByteString
      getSerialNoBytes();

  /**
   * <code>string config_topic = 2;</code>
   */
  java.lang.String getConfigTopic();
  /**
   * <code>string config_topic = 2;</code>
   */
  com.google.protobuf.ByteString
      getConfigTopicBytes();

  /**
   * <code>string data_topic = 3;</code>
   */
  java.lang.String getDataTopic();
  /**
   * <code>string data_topic = 3;</code>
   */
  com.google.protobuf.ByteString
      getDataTopicBytes();

  /**
   * <code>.thermostat.app.ProvisioningResponse.ProvStatus status = 4;</code>
   */
  int getStatusValue();
  /**
   * <code>.thermostat.app.ProvisioningResponse.ProvStatus status = 4;</code>
   */
  com.sid.thermostat.app.protobuf.ProvisioningResponse.ProvStatus getStatus();

  /**
   * <code>int32 qos = 5;</code>
   */
  int getQos();
}
